train: [] # metrics that are calculated during training
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.BeamSearchCERMetric
    name: "CER_(BeamSearch)" # it is better to avoid spaces in names
  - _target_: src.metrics.BeamSearchWERMetric
    name: "WER_(BeamSearch)"
